name: Build Bluefin LTS HWE

permissions:
  contents: read
  packages: write
  id-token: write

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 1 * * TUE" # Every Tuesday at 1am UTC
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    with:
      image-name: bluefin
      rechunk: ${{ github.event_name != 'pull_request' }}
      sbom: ${{ github.event_name != 'pull_request' }}
      publish: ${{ github.event_name != 'pull_request' }}
      hwe: true
  tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Tag image
        id: tag
        run: |
          echo "Tagging hwe image with testing suffix"
          docker tag bluefin:lts-hwe  bluefin:lts-testing

      - name: Push tagged image
        run: |
          echo "Pushing tagged image"
          docker push bluefin:lts-testing
