name: Build Bluefin DX LTS HWE

permissions:
  contents: read
  packages: write
  id-token: write

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 1 * * TUE" # Every Tuesday at 1am UTC
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    with:
      image-name: bluefin-dx
      flavor: dx
      rechunk: ${{ github.event_name != 'pull_request' }}
      sbom: ${{ github.event_name != 'pull_request' }}
      publish: ${{ github.event_name != 'pull_request' }}
      hwe: true
  tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag image
        id: tag
        run: |
          echo "Tagging hwe image with testing suffix"
          docker tag bluefin-dx:lts-hwe  bluefin-dx:lts-testing

      - name: Push tagged image
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "Pushing tagged image"
          docker push bluefin-dx:lts-testing
